name: CI/CD with Docker

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: sathwikreddy/myimage:latest

    - name: Stop Old Docker Container
      run: docker stop mycontainer || true

    - name: Remove Old Docker Container
      run: docker rm mycontainer || true

    - name: Start New Docker Container
      run: docker run -p 5000:5000 --name mycontainer sathwikreddy/myimage:latest
